config/routes.rb
Rails.application.routes.draw do
  root to: 'home#top'
  get '/about', to: 'pages#about'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :users, only: :show
  resources :groups, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :destinations
  resources :plans, only: [:new, :create, :show, :edit, :update, :destroy] do
    member do
      get 'edit_status'
      patch 'update_status'
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users, dependent: :destroy
  has_many :plans, dependent: :destroy

  validates :name, presence: :true, length: { maximum: 15 }
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :group
  has_many :plan_destinations
  has_many :destinations, through: :plan_destinations, dependent: :destroy
  has_many_attached :images

  validates :title, presence: true, length: { maximum: 25 }
  validates :start_date, :end_date, presence: true
  validates :images, content_type: { in: ['image/png', 'image/jpeg'], message: 'の形式が対応していません。対応形式はPNGまたはJPEGです。' }
  validate :start_date_is_before_end_date
  validate :no_more_than_3_photos

  def start_date_is_before_end_date
    if start_date.present? && end_date.present? && start_date > end_date
      errors.add(:end_date, "は開始日より後の日付にしてください。")
    end
  end

  def no_more_than_3_photos
    if images.attached? && images.count > 3
      errors.add(:images, "は3枚以内にしてください。")
    end
  end

  def self.generate_travel_plan(destinations, start_date, end_date)
    client = OpenAI::Client.new
    response = client.chat(
      parameters: {
        model: "gpt-3.5-turbo",
        messages: [
          {
            role: "system",
            content: "あなたは優秀な旅行プランナーです。条件を基に、あなたのおすすめも行程に盛り込みながら、最適な旅行プランを500文字以内の日本語で提案してください。",
          },
          {
            role: "user",
            content: <<~TEXT,
            旅程は、#{start_date}から#{end_date}です。絶対に立ち寄る場所は、#{destinations}です。

            以下の条件に従って、旅行プランを作成してください：
            - 昼食、夕食にはできるだけその土地のグルメを楽しむ
            - 各スポットや追加のおすすめについて、数行で詳細を説明する
            - 見出しや改行を使って読みやすくする
            - 最後に、その土地の紹介とお土産等の追加の旅行ポイントも教えてください
          TEXT
          },
        ],
      }
    )
    response.dig("choices", 0, "message", "content")
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params_with_current_user)
    if @group.save
      flash[:notice] = "「#{@group.name}」を登録しました"
      redirect_to group_path(@group)
    else
      flash.now[:alert] = "グループの登録に失敗しました"
      render "groups/new"
    end
  end

  def show
    @group = Group.find(params[:id])
    @member = @group.users.includes(:icon_attachment)
    @plans = @group.plans.includes(images_attachments: :blob).order(start_date: :desc)
    group_users = @group.users.includes(:destinations)

    # 都道府県の絞り込み機能
    if params[:prefecture].present?
      @visible_destinations = group_users.index_with do |user|
        user.destinations.where(is_private: false).where("address LIKE ?", "%#{params[:prefecture]}%").order(created_at: :desc)
      end
    else
      @visible_destinations = group_users.index_with do |user|
        user.destinations.where(is_private: false).order(created_at: :desc)
      end
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params_with_current_user)
      flash[:notice] = "「#{@group.name}」を更新しました"
      redirect_to group_path(@group)
    else
      flash.now[:alert] = "グループの更新に失敗しました"
      render "groups/edit"
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    flash[:notice] = "「#{@group.name}」を削除しました"
    redirect_to user_path(current_user.id)
  end

  private

  def group_params
    params.require(:group).permit(:name, { user_ids: [] })
  end

  def group_params_with_current_user
    params = group_params
    params[:user_ids] << current_user.id
    params
  end
end

app/views/groups/edit.html.erb
<% provide(:title, "グループを編集") %>
<div class="container my-2 my-md-4" style="max-width: 768px;">
  <div class="row py-3 py-md-5 d-flex justify-content-center shadow-sm rounded-3 bg-white">
    <div class="col-11 col-sm-9 col-md-8 p-0">
      <h4 class="mb-4 fw-bold text-center">
        <i class="bi bi-pencil-fill"></i>
        グループを編集
      </h4>
      <%= render "shared/errors", obj: @group %>
      <%= form_with model: @group do |f| %>
        <div class="mb-4">
          <%= f.label :name, class: "required" %>
          <span class="character-limit">15文字以内</span>
          <%= f.text_field :name, placeholder: "グループ名を入力", class: "form-control form-control-sm" %>
        </div>
        <p class="small mb-2">ユーザーを選択して下さい。</p>
        <div class="mb-4">
          <%= f.collection_check_boxes :user_ids, User.all, :id, :name, { disabled: current_user.id } do |b| %>
            <span class="check-boxes me-3"><%= b.label { b.check_box + b.text } %></span>
          <% end %>
        </div>
        <div class="mb-3 d-flex gap-2">
          <%= link_to group_path, method: :delete, data: { confirm: "「#{@group.name}」を削除しますか？" },
           class: "btn btn-sm btn-outline-secondary rounded-pill col fs-6 d-flex justify-content-center align-items-center gap-1" do %>
            <i class="bi bi-trash"></i>グループ削除
          <% end %>
          <%= button_tag type: "submit",
           class: "btn btn-sm btn-danger rounded-pill col fs-6 d-flex justify-content-center align-items-center gap-1" do %>
            <i class="bi bi-check2-circle fs-5"></i>保存
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<% provide(:title, "グループを作成") %>
<div class="container my-2 my-md-4" style="max-width: 768px;">
  <div class="row py-3 py-md-5 d-flex justify-content-center shadow-sm rounded-3 bg-white">
    <div class="col-11 col-sm-9 col-md-8 p-0">
      <h4 class="mb-4 fw-bold text-center">
        <i class="bi bi-people-fill"></i>
        グループを作成
      </h4>
      <%= render "shared/errors", obj: @group %>
      <%= form_with model: @group do |f| %>
        <div class="mb-4">
          <%= f.label :name, class: "required" %>
          <span class="character-limit">15文字以内</span>
          <%= f.text_field :name, autofocus: true, placeholder: "グループ名を入力", class: "form-control form-control-sm" %>
        </div>
        <p class="small mb-2">追加するユーザーを選択して下さい。</p>
        <div class="mb-4">
          <%= f.collection_check_boxes :user_ids, User.all, :id, :name, { checked: current_user.id, disabled: current_user.id } do |b| %>
            <span class="check-boxes me-3"><%= b.label { b.check_box + b.text } %></span>
          <% end %>
        </div>
        <div class="mb-3 d-grid gap-2">
          <%= f.submit "作成", class: "btn btn-danger rounded-pill" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<% provide(:title, @group.name) %>
<div class="container-md mt-3 mt-md-4">
  <div class="row d-flex justify-content-center">
    <div class="col-11 col-md-12 px-0">
      <h2 class="group-name fw-bold mb-md-0 text-center"><%= @group.name %></h2>
      <%= link_to edit_group_path(@group), class: "d-block text-end text-decoration-none me-2" do %>
        <i class="bi bi-pen"></i>
        グループを編集
      <% end %>
    </div>
  </div>
</div>

<div class="container-md mt-2">
  <div class="row">
    <div class="col-12 col-lg-5 px-md-0 pe-lg-3">
      <div class="px-2 pt-3 pt-lg-4 bg-white shadow-sm rounded-3 h-100">
        <h5 class="fw-bold d-flex justify-content-center align-items-center gap-1 mb-3">
          <i class="bi bi-people-fill fs-4"></i>
          メンバー
        </h5>
        <table class="table table-sm">
          <% @member.each do |member| %>
            <tr>
              <% if member.icon.attached? %>
                <td><%= image_tag member.icon.variant(resize: '100x100'), alt: "アイコン", class: "group-icon rounded-circle" %></td>
              <% else %>
                <td><%= image_tag 'icon_user.png', alt: "サンプルアイコン", class: "group-icon rounded-circle" %></td>
              <% end %>
              <td><%= member.name %></td>
              <td class="text-nowrap text-secondary"><%= member.prefecture.present? ? member.prefecture.name : "-" %></td>
              <td class="d-none d-sm-table-cell"><%= member.introduction.present? ? member.introduction : "-" %></td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>

    <div class="col-12 col-lg-7 px-md-0">
      <div class="mt-3 mt-lg-0 py-3 py-lg-4 px-2 bg-white shadow-sm rounded-3">
        <div class="d-md-flex d-lg-block d-xxl-flex justify-content-between align-items-center">
          <h5 class="d-flex gap-1 fw-bold mb-3 mb-md-0 mb-lg-3 mb-xxl-0">
            <i class="bi bi-geo-alt-fill fs-4"></i>
            目的地を選択して、旅行プランを作成しよう
          </h5>
          <%= form_with url: group_path(@group.id), method: :get do |f| %>
            <div class="d-flex justify-content-end align-items-center gap-1">
              <%= f.collection_select(:prefecture, JpPrefecture::Prefecture.all, :name, :name, { prompt: "都道府県を選択" }, { class: "form-select form-select-sm w-auto" }) %>
              <%= f.submit "絞り込む", class: "btn btn-dark btn-sm bg-gradient" %>
            </div>
          <% end %>
        </div>
        <div class="d-flex justify-content-end">
          <% if params[:prefecture].present? %>
            <div class="alert alert-info px-2 py-1 mt-2 mb-0">
              <i class="bi bi-funnel-fill"></i>
              <span>選択中：<%= params[:prefecture] %></span>
              <%= link_to group_path(@group.id) do %>
                <i class="bi bi-x-lg alert-link"></i>
              <% end %>
            </div>
          <% end %>
        </div>

        <div class="mt-3">
          <%= form_with url: new_plan_path, method: :get do |f| %>
            <div class="select-destinations border py-2 px-1 px-sm-3 px-xl-4 mx-sm-2">
              <% @visible_destinations.each do |user, destinations| %>
                <p class="fw-bold mb-2"><%= user.name %></p>
                <ul class="ps-2 ps-sm-4">
                  <% destinations.each do |destination| %>
                    <li class="list-unstyled">
                      <%= check_box_tag "destination_ids[]", destination.id, false, id:"destination_#{destination.id}", class: "form-check-input" %>
                      <%= label_tag "destination_#{destination.id}", destination.name %>
                      <%= link_to "詳細", destination_path(destination.id) %>
                    </li>
                  <% end %>
                </ul>
              <% end %>
            </div>
            <%= f.hidden_field :group_id, value: @group.id %>
            <div class="d-grid mt-4 mt-md-5 px-3">
              <%= f.submit '旅行プラン作成に進む', class: "btn btn-outline-dark rounded-pill shadow-sm" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container-md mt-4">
  <div class="row d-flex justify-content-center">
    <div class="col-12 px-md-0 mt-2 mb-4">
      <h4 class="mb-3 fw-bold text-center">
        <i class="bi bi-airplane-fill"></i>
        このグループの旅行プラン
      </h4>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-lg-3 row-cols-xxl-4 g-4 plan-list">
        <% @plans.each do |plan| %>
            <div class="col">
              <div class="card h-100 shadow-sm">
                <%= link_to plan_path(plan) do %>
                  <% if plan.images.present? %>
                    <%= image_tag plan.images.sample, alt: "思い出の写真", class: "border-bottom plan-card-image" %>
                  <% else %>
                    <%= image_tag 'logo_2.jpg', alt: "サンプル写真", class: "border-bottom plan-card-image sample-card-image" %>
                  <% end %>
                <% end %>
                <div class="card-body">
                  <h5 class="card-title fw-bold">
                    <%= link_to plan.title, plan_path(plan) %>
                  </h5>
                  <h6 class="card-subtitle mb-2 text-muted">
                    <i class="bi bi-calendar-range me-1"></i>
                    <%= l plan.start_date %> - <%= l plan.end_date, format: :short %>
                  </h6>
                  <% if plan.status == "実行済" %>
                    <div class="alert alert-info p-0 mb-0 d-flex justify-content-center align-items-center gap-1" role="alert">
                      <i class="bi bi-check2-circle fs-4"></i>
                      <%= plan.status %>
                    </div>
                  <% end %>
                  <p class="mt-2 mb-0 limit-3rows"><%= plan.note %></p>
                </div>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>