config/routes.rb
Rails.application.routes.draw do
  root to: 'home#top'
  get '/about', to: 'pages#about'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :users, only: :show
  resources :groups, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :destinations
  resources :plans, only: [:new, :create, :show, :edit, :update, :destroy] do
    member do
      get 'edit_status'
      patch 'update_status'
    end
  end
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :user
  belongs_to :category, optional: true
  has_many :plan_destinations
  has_many :plans, through: :plan_destinations, dependent: :destroy

  validate :encourage_search_on_maps
  validates :name, length: { maximum: 20 }
  validates :address, length: { maximum: 60 }

  def self.extract_prefecture_code(address)
    @prefectures ||= JpPrefecture::Prefecture.all
    @prefectures.each do |pref|
      return pref.code if address.include?(pref.name)
    end
    nil # 都道府県名に一致しなかった場合
  end

  def encourage_search_on_maps
    if name.blank? || address.blank? || latitude.blank? || longitude.blank?
      if @new_record
        errors.add(:base, "Googleマップで場所を検索してください。一部項目が自動入力されます。（編集可）")
      else
        errors.add(:base, "場所の名前、住所は空欄にできません")
      end
    end
  end
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :authenticate_user!

  def index
    if params[:category_id].present?
      @destinations = current_user.destinations.where(category_id: params[:category_id]).order(created_at: :desc)
      @category = Category.find(params[:category_id])
    else
      @destinations = current_user.destinations.order(created_at: :desc)
    end
  end

  def new
    @destination = Destination.new
    # アクションに応じてバリデーションエラーメッセージを変更
    @new_record = true
  end

  def create
    @destination = Destination.new(destination_params)
    if @destination.save
      flash[:notice] = "「#{@destination.name}」を登録しました。"
      redirect_to destinations_path
    else
      flash.now[:alert] = "行きたいところの登録に失敗しました"
      render "destinations/new"
    end
  end

  def show
    @destination = Destination.find(params[:id])
    @destinations = current_user.destinations.order(created_at: :desc)
  end

  def edit
    @destination = Destination.find(params[:id])
    # アクションに応じてバリデーションエラーメッセージを変更
    @new_record = false
  end

  def update
    @destination = Destination.find(params[:id])
    if @destination.update(destination_params)
      flash[:notice] = "「#{@destination.name}」を更新しました。"
      redirect_to destinations_path
    else
      flash.now[:alert] = "行きたいところの更新に失敗しました。"
      render "destinations/edit"
    end
  end

  def destroy
    @destination = Destination.find(params[:id])
    @destination.destroy
    flash[:notice] = "行きたいリストから「#{@destination.name}」を削除しました。"
    redirect_to destinations_path
  end

  private

  def destination_params
    params.require(:destination).permit(:name, :address, :note, :is_private, :latitude, :longitude, :status, :user_id,
:category_id)
  end
end

app/views/destinations/edit.html.erb
<% provide(:title, "行きたい場所を編集") %>
<div id='map'></div>
<script>
  let map
  let marker
  function initMap(){
    geocoder = new google.maps.Geocoder()
    map = new google.maps.Map(document.getElementById('map'), {
      center:  {lat: <%= @destination.latitude %>, lng: <%= @destination.longitude %>},
      zoom: 15,
    });
    marker = new google.maps.Marker({
      position:  {lat: <%= @destination.latitude %>, lng: <%= @destination.longitude %>},
      draggable: true,
      map: map
    });
    // マーカーのドロップ（ドラッグ終了）時のイベント
    google.maps.event.addListener( marker, 'dragend', function(ev){
      document.getElementById('lat').value = ev.latLng.lat();
      document.getElementById('lng').value = ev.latLng.lng();
    });
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['MAPS_PLATFORM_API_KEY'] %>&callback=initMap" async defer></script>

<div class="container my-md-3" style="max-width: 768px;">
  <div class="row py-4 d-flex justify-content-center shadow-sm rounded-3 bg-white">
    <div class="col-11 col-sm-7 col-md-6 p-0">
      <h4 class="mb-3 fw-bold text-center">
        <i class="bi bi-pencil-fill me-1"></i>
        行きたい場所を編集
      </h4>
      <p class="mb-4 d-flex justify-content-center align-items-center gap-1">
        <i class="bi bi-geo-alt-fill fs-5"></i>
        マーカーを動かすと地点を微調整できます。
      </p>
      <%= render "shared/errors", obj: @destination %>
      <%= form_with model: @destination do |f| %>
        <div class="mb-3">
          <%= f.label :name, "名称", class: "required" %>
          <span class="character-limit">20文字以内</span>
          <%= f.text_field :name, id: :name, placeholder: "Googleマップから自動入力（編集可）", class: "form-control form-control-sm" %>
        </div>
        <div class="mb-4">
          <%= f.label :address, class: "required" %>
          <span class="character-limit">60文字以内</span>
          <%= f.text_field :address, id: :address_on_map, placeholder: "Googleマップから自動入力（編集可）", class: "form-control form-control-sm" %>
        </div>
        <div class="mb-3 d-flex align-items-center gap-3">
          <%= f.label :category_id, "カテゴリー", class: "text-nowrap" %>
          <%= f.collection_select(:category_id, Category.all, :id, :name, { prompt: "カテゴリーを選択" }, { class: "form-select form-select-sm" }) %>
        </div>
        <div class="mb-3">
          <%= f.label :note %>
          <%= f.text_area :note, class: "form-control form-control-sm" %>
        </div>
        <div class="mb-3 form-check">
          <%= f.check_box :is_private, {class: "form-check-input"}, "true", "false" %>
          <%= f.label :is_private, "非公開にする場合はチェック", class: "form-check-label" %>
        </div>
        <%= f.hidden_field :latitude, id: :lat %>
        <%= f.hidden_field :longitude, id: :lng %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <div class="mb-3 d-flex gap-3">
          <%= link_to destination_path, method: :delete, data: { confirm: "「#{@destination.name}」を削除しますか？" },
           class: "btn btn-sm btn-outline-secondary rounded-pill col fs-6 d-flex justify-content-center align-items-center gap-1" do %>
            <i class="bi bi-trash"></i>リストから削除
          <% end %>
          <%= button_tag type: "submit",
           class: "btn btn-sm btn-danger rounded-pill col fs-6 d-flex justify-content-center align-items-center gap-1" do %>
            <i class="bi bi-check2-circle fs-5"></i>保存
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/destinations/index.html.erb
<% provide(:title, "行きたいリスト") %>
<div id='map'></div>
<script>
  function initMap() {
    let map = new google.maps.Map(document.getElementById('map'), {
      center: {
        lat: <%= @destinations.present? ? @destinations.first.latitude : 34.7024854 %>,
        lng: <%= @destinations.present? ? @destinations.first.longitude : 135.4959506 %>
      },
      zoom: 10,
    });
    let transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);

    <% @destinations.each do |destination| %>
      (function() {
        let markerLatLng = { lat: <%= destination.latitude %>, lng: <%= destination.longitude %> };
        let marker = new google.maps.Marker({
          position: markerLatLng,
          map: map
        });
        //マーカーをクリックしたとき、詳細情報を表示
        let infowindow = new google.maps.InfoWindow({
          position: markerLatLng,
          content: "<a href='<%= destination_url(destination.id) %>'><%= destination.name %></a>"
        }); //詳細ページへのリンクを表示
        marker.addListener('click', function() {
          infowindow.open(map, marker);
        });
      })();
    <% end %>
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['MAPS_PLATFORM_API_KEY'] %>&callback=initMap" async defer></script>

<div class="container-md mt-2">
  <div class="row">
    <div class="col-12 p-2 bg-white shadow-sm rounded-3">
      <div class="d-md-flex justify-content-between align-items-center gap-2 mb-3">
        <h4 class="mb-md-0"><%= current_user.name %>さんの行きたいリスト</h4>
        <%= form_with url: destinations_path, method: :get do |f| %>
          <div class="d-flex justify-content-end align-items-center gap-1">
            <%= f.collection_select(:category_id, Category.all, :id, :name, { prompt: "カテゴリーを選択" }, { class: "form-select form-select-sm w-auto" }) %>
            <%= f.submit "絞り込む", class: "btn btn-secondary btn-sm" %>
          </div>
        <% end %>
      </div>
      <div class="d-flex justify-content-between align-items-center">
        <%= link_to new_destination_path, class: "btn btn-success btn-sm rounded-pill" do %>
          <i class="bi bi-geo-alt-fill"></i>
          <span>行きたい場所を登録</span>
        <% end %>
        <% if params[:category_id].present? %>
          <div class="alert alert-info px-2 py-1 m-0">
            <i class="bi bi-funnel-fill"></i>
            <span>選択中：<%= @category.name %></span>
            <%= link_to destinations_path do %>
              <i class="bi bi-x-lg alert-link"></i>
            <% end %>
          </div>
        <% end %>
      </div>
      <table class="table table-striped text-nowrap mt-3 destinations-table">
        <% @destinations.each do |destination| %>
          <tr>
            <th class="destn-name-col txt-limit"><%= link_to destination.name, destination_path(destination.id) %></th>
            <td class="d-none d-sm-table-cell txt-limit"><%= destination.note.present? ? destination.note : "-" %></td>
            <td class="private-col ">
              <span class="badge bg-secondary rounded-pill"><%= "非公開" if destination.is_private %></span>
            </td>
            <td class="edit-link-col"><%= link_to "編集", edit_destination_path(destination.id) %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/destinations/new.html.erb
<% provide(:title, "行きたい場所を登録") %>
<div id='map'></div>
<script>
  //初期マップの設定
  let map
  let marker
  function initMap(){
    geocoder = new google.maps.Geocoder()
    map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: 34.7024854, lng: 135.4959506},
      zoom: 15,
    });
  }

  //検索後のマップ作成
  let geocoder
  let aft
  function codeAddress(){
    let inputAddress = document.getElementById('address').value;
    geocoder.geocode( { 'address': inputAddress}, function(results, status) {
      if (status == 'OK') {
        //マーカーが複数できないようにする
        if (aft == true){
            marker.setMap(null);
        }
        //新しくマーカーを作成する
        map.setCenter(results[0].geometry.location);
          marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location,
          draggable: true
        });
        //二度目以降か判断
        aft = true
        //検索時に緯度・経度・場所の名前・住所を入力する
        document.getElementById('lat').value = results[0].geometry.location.lat();
        document.getElementById('lng').value = results[0].geometry.location.lng();
        document.getElementById('name').value = inputAddress;
        document.getElementById('address_on_map').value = results[0].formatted_address;
        // マーカーのドロップ（ドラッグ終了）時のイベント
        google.maps.event.addListener( marker, 'dragend', function(ev){
          document.getElementById('lat').value = ev.latLng.lat();
          document.getElementById('lng').value = ev.latLng.lng();
        });
      } else {
        alert('該当する情報が見つかりませんでした。');
      }
    });
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['MAPS_PLATFORM_API_KEY'] %>&callback=initMap" async defer></script>

<div class="container my-md-3" style="max-width: 768px;">
  <div class="row py-4 d-flex justify-content-center shadow-sm rounded-3 bg-white">
    <div class="col-10 col-sm-7 col-md-6 p-0">
      <h4 class="mb-4 fw-bold text-center">
        行きたい場所を登録
      </h4>
      <%= render "shared/errors", obj: @destination %>
      <div class="d-flex">
        <input id="address" class="form-control form-control-sm me-2" type="textbox" placeholder="まずはGoogleマップで検索！" autofocus=true>
        <input type="button" value="検 索" class="btn btn-success px-4" onclick="codeAddress()">
      </div>
      <p class="mt-2 mb-4 d-flex justify-content-center gap-1">
        <i class="bi bi-geo-alt-fill"></i>
        マーカーを動かすと地点を微調整できます。
      </p>
      <%= form_with model: @destination do |f| %>
        <div class="mb-3">
          <%= f.label :name, "名称", class: "required" %>
          <span class="character-limit">20文字以内</span>
          <%= f.text_field :name, id: :name, placeholder: "検索内容が転記されます（編集可）", class: "form-control form-control-sm" %>
        </div>
        <div class="mb-4">
          <%= f.label :address, class: "required" %>
          <span class="character-limit">60文字以内</span>
          <%= f.text_field :address, id: :address_on_map, placeholder: "Googleマップから自動入力（編集可）", class: "form-control form-control-sm" %>
        </div>
        <div class="mb-3 d-flex align-items-center gap-3">
          <%= f.label :category_id, "カテゴリー", class: "text-nowrap" %>
          <%= f.collection_select(:category_id, Category.all, :id, :name, { prompt: "カテゴリーを選択" }, { class: "form-select form-select-sm" }) %>
        </div>
        <div class="mb-3">
          <%= f.label :note %>
          <%= f.text_area :note, class: "form-control form-control-sm" %>
        </div>
        <div class="mb-3 form-check">
          <%= f.check_box :is_private, {class: "form-check-input"}, "true", "false" %>
          <%= f.label :is_private, "非公開にする場合はチェック", class: "form-check-label" %>
        </div>
        <%= f.hidden_field :latitude, id: :lat %>
        <%= f.hidden_field :longitude, id: :lng %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <div class="d-grid gap-2">
          <%= f.submit '保存', class: "btn btn-danger rounded-pill" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/destinations/show.html.erb
<% provide(:title, @destination.name) %>
<div class="container-fluid">
  <div class="row">
    <div class="col-4 col-xl-3 d-none d-sm-block ps-0 pe-lg-5">
      <h5 class="text-center mt-3 px-1">
        <i class="bi bi-person-lines-fill fs-4"></i>
        <%= current_user.name %>
        <span class="fs-6 text-nowrap">さんの行きたいリスト</span>
      </h5>
      <ul class="list-group">
        <% @destinations.each do |destination| %>
          <li class="list-group-item list-group-item-action list-group-item-light<%= " active" if destination.id == @destination.id %> d-flex justify-content-between align-items-center pe-2">
            <%= link_to destination.name, destination_path(destination.id), class: (destination.id == @destination.id ? "text-white" : "text-body") %>
            <% if destination.is_private %>
              <span class="badge bg-dark rounded-pill">非公開</span>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="col-12 col-sm-8 col-xl-9 mt-sm-3">
      <div class="row">
        <div class="col-12 col-sm-11 p-0" style="max-width:800px;">
          <div id='map'></div>
          <script>
            let map
            let marker
            function initMap(){
              geocoder = new google.maps.Geocoder()
              map = new google.maps.Map(document.getElementById('map'), {
                center:  {lat: <%= @destination.latitude %>, lng: <%= @destination.longitude %>},
                zoom: 15,
              });
              marker = new google.maps.Marker({
                position:  {lat: <%= @destination.latitude %>, lng: <%= @destination.longitude %>},
                map: map
              });
            }
          </script>
          <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['MAPS_PLATFORM_API_KEY'] %>&callback=initMap" async defer></script>
        </div>
      </div>
      <div class="row">
        <div class="col-12 col-sm-11 p-3 p-md-4 shadow-sm rounded-3 bg-white" style="max-width:800px;">
          <div class="d-flex justify-content-between align-items-center gap-2 mb-3">
            <div class="d-flex align-items-center gap-2 gap-md-3">
              <h4 class="mb-0"><%= @destination.name %></h4>
              <% if @destination.is_private %>
                <span class="badge bg-dark rounded-pill">非公開</span>
              <% else %>
                <span class="mb-0 text-nowrap badge <%= @destination.status == "未訪問" ? "bg-danger" : "bg-secondary" %> px-2 py-1">
                  <%= @destination.status %>
                </span>
              <% end %>
            </div>
            <% if @destination.category.present? %>
              <span class="text-nowrap badge bg-light text-dark p-2 border">
                <%= @destination.category.name %>
              </span>
            <% end %>
          </div>
          <p class="text-secondary mb-0"><%= @destination.address %></p>
          <% if @destination.note.present? %>
            <p class="mt-3 mb-0"><%= @destination.note %></p>
          <% end %>
          <div class="d-flex justify-content-end">
            <% if @destination.user.id == current_user.id %>
              <%= link_to edit_destination_path(@destination.id), class: "text-decoration-none mt-2" do %>
                <i class="bi bi-pencil-fill"></i>
                編集
              <% end %>
            <% else %>
              <div class="d-flex align-items-center gap-1 mt-3">
                <% if @destination.user.icon.attached? %>
                  <%= image_tag @destination.user.icon, alt: "アイコン", class: "group-icon rounded-circle" %>
                <% else %>
                  <%= image_tag 'icon_user.png', alt: "サンプルアイコン", class: "group-icon rounded-circle" %>
                <% end %>
                <span class=""><%= @destination.user.name %></span>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>