config/routes.rb
Rails.application.routes.draw do
  root to: 'home#top'
  get '/about', to: 'pages#about'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :users, only: :show
  resources :groups, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :destinations
  resources :plans, only: [:new, :create, :show, :edit, :update, :destroy] do
    member do
      get 'edit_status'
      patch 'update_status'
    end
  end
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :group
  has_many :plan_destinations
  has_many :destinations, through: :plan_destinations, dependent: :destroy
  has_many_attached :images

  validates :title, presence: true, length: { maximum: 25 }
  validates :start_date, :end_date, presence: true
  validates :images, content_type: { in: ['image/png', 'image/jpeg'], message: 'の形式が対応していません。対応形式はPNGまたはJPEGです。' }
  validate :start_date_is_before_end_date
  validate :no_more_than_3_photos

  def start_date_is_before_end_date
    if start_date.present? && end_date.present? && start_date > end_date
      errors.add(:end_date, "は開始日より後の日付にしてください。")
    end
  end

  def no_more_than_3_photos
    if images.attached? && images.count > 3
      errors.add(:images, "は3枚以内にしてください。")
    end
  end

  def self.generate_travel_plan(destinations, start_date, end_date)
    client = OpenAI::Client.new
    response = client.chat(
      parameters: {
        model: "gpt-3.5-turbo",
        messages: [
          {
            role: "system",
            content: "あなたは優秀な旅行プランナーです。条件を基に、あなたのおすすめも行程に盛り込みながら、最適な旅行プランを500文字以内の日本語で提案してください。",
          },
          {
            role: "user",
            content: <<~TEXT,
            旅程は、#{start_date}から#{end_date}です。絶対に立ち寄る場所は、#{destinations}です。

            以下の条件に従って、旅行プランを作成してください：
            - 昼食、夕食にはできるだけその土地のグルメを楽しむ
            - 各スポットや追加のおすすめについて、数行で詳細を説明する
            - 見出しや改行を使って読みやすくする
            - 最後に、その土地の紹介とお土産等の追加の旅行ポイントも教えてください
          TEXT
          },
        ],
      }
    )
    response.dig("choices", 0, "message", "content")
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :group_users
  has_many :groups, through: :group_users, dependent: :destroy
  has_many :destinations, dependent: :destroy
  has_one_attached :icon

  validates :name, presence: :true, length: { maximum: 15 }
  validates :introduction, length: { maximum: 80 }

  devise :database_authenticatable, :registerable,
         :rememberable, :validatable, :trackable

  include JpPrefecture
  jp_prefecture :prefecture_code

  def self.guest
    find_or_create_by(email: 'guest@example.com') do |user|
      user.name = "ゲスト"
      user.prefecture_code = 27
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :authenticate_user!

  def new
    @plan = Plan.new
    @group_id = params[:group_id]
    # パラメータはgroups#showのフォームから送られたもの
    @selected_destinations = Destination.where(id: params[:destination_ids])
  end

  def create
    selected_destination_names = Destination.where(id: plan_params[:destination_ids].reject(&:blank?)).pluck(:name)

    if selected_destination_names.blank?
      flash[:alert] = "目的地が選択されていません。"
      return redirect_to group_path(plan_params[:group_id])
    end

    @plan = Plan.new(plan_params)
    if @plan.save
      # バリデーションをパスした場合のみAI提案プランを生成
      @plan.update(proposed_plan: Plan.generate_travel_plan(selected_destination_names, @plan.start_date, @plan.end_date))
      flash[:notice] = "「#{@plan.title}」を作成しました"
      redirect_to plan_path(@plan)
    else
      @group_id = plan_params[:group_id]
      @selected_destinations = Destination.where(id: plan_params[:destination_ids])
      flash.now[:alert] = "旅行プランの作成に失敗しました"
      render "plans/new"
    end
  end

  def show
    @plan = Plan.includes(images_attachments: :blob).find(params[:id])
    @my_plans = Plan.where(group_id: current_user.groups)
    @plan_destinations = @plan.destinations.includes(:category, :user).order('categories.name')
  end

  def edit
    @plan = Plan.find(params[:id])
  end

  def update
    @plan = Plan.find(params[:id])
    if @plan.update(plan_params)
      flash[:notice] = "「#{@plan.title}」を更新しました。"
      redirect_to plan_path(@plan)
    else
      flash.now[:alert] = "旅行プランの更新に失敗しました。"
      render "plans/edit"
    end
  end

  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy
    flash[:notice] = "「#{@plan.title}」を削除しました。"
    redirect_to group_path(@plan.group_id)
  end

  def edit_status
    @plan = Plan.find(params[:id])
    @destinations = @plan.destinations
  end

  def update_status
    @plan = Plan.find(params[:id])
    visited_destinations = plan_params[:destination_ids].reject(&:blank?)
    if @plan.update(status_params)
      @plan.destinations.where(id: visited_destinations).update_all(status: "訪問済")
      @plan.destinations.where.not(id: visited_destinations).update_all(status: "未訪問")
      flash[:notice] = "「#{@plan.title}」と選択した行きたいリストのステータスを更新しました。"
      redirect_to group_path(@plan.group_id)
    else
      @destinations = @plan.destinations
      flash.now[:alert] = "旅行プラン・目的地のステータス更新に失敗しました。"
      render "plans/edit_status"
    end
  end

  private

  def plan_params
    params.require(:plan).permit(:title, :note, :start_date, :end_date, :proposed_plan, :status, :group_id, destination_ids: [])
  end

  def status_params
    params.require(:plan).permit(:status, images: [])
  end
end

app/views/plans/edit.html.erb
<% provide(:title, "旅行プラン編集") %>
<div class="container my-2 my-md-4" style="max-width: 900px;">
  <div class="row py-4 d-flex justify-content-center shadow-sm rounded-3 bg-white">
    <div class="col-11 col-sm-9 col-md-8 p-0">
      <h4 class="mb-4 fw-bold text-center">
        <i class="bi bi-pencil-fill me-1"></i>
        旅行プラン編集
      </h4>
      <p class="text-secondary text-md-center mb-4">
        <i class="bi bi-chat-dots fs-5"></i>
        AI提案プランを生成するには、旅行プランを新たに作成して下さい。
      </p>
      <%= render "shared/errors", obj: @plan %>
      <%= form_with model: @plan do |f| %>
        <div class="mb-4">
          <%= f.label :title, class: "required" %>
          <span class="character-limit">25文字以内</span>
          <%= f.text_field :title, placeholder: "例）AI大阪旅", class: "form-control form-control-sm" %>
        </div>
        <%= f.label :start_date, "期間", class: "required" %>
        <div class="mb-3 d-flex justify-content-between align-items-center gap-1 gap-sm-4">
          <%= f.date_field :start_date, class: "form-control form-control-sm" %>
          <span class="text-nowrap">から</span>
          <%= f.date_field :end_date, class: "form-control form-control-sm" %>
        </div>
        <div class="mb-3">
          <p class="mb-1">こちらが選択されています</p>
          <%= f.collection_check_boxes :destination_ids, @plan.destinations, :id, :name do |b| %>
            <span class="check-boxes me-2"><%= b.label { b.check_box(checked: true) + b.text } %></span>
          <% end %>
        </div>
        <div class="mb-3">
          <%= f.label :proposed_plan %>
          <%= f.text_area :proposed_plan, placeholder: "AIで文章を生成するには、旅行プランを改めて作成し直して下さい。", class: "form-control form-control-sm", rows: 15 %>
        </div>
        <div class="mb-4">
          <%= f.label :note %>
          <%= f.text_area :note, placeholder: "旅のメモを入力", class: "form-control form-control-sm" %>
        </div>
        <div class="mb-3 d-flex gap-3">
          <%= link_to plan_path, method: :delete, data: { confirm: "「#{@plan.title}」を削除しますか？" },
           class: "btn btn-sm btn-outline-secondary rounded-pill col fs-6 d-flex justify-content-center align-items-center gap-1" do %>
            <i class="bi bi-trash"></i>旅行プラン削除
          <% end %>
          <%= button_tag type: "submit",
           class: "btn btn-sm btn-danger bg-gradient rounded-pill col fs-6 d-flex justify-content-center align-items-center gap-1" do %>
            <i class="bi bi-check2-circle fs-5"></i>保存
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/plans/edit_status.html.erb
<% provide(:title, "旅行が終わったら") %>
<div class="container my-2 my-md-4" style="max-width: 900px;">
  <div class="row py-5 d-flex justify-content-center shadow-sm rounded-3 bg-white">
    <div class="col-11 col-sm-9 col-md-8 p-0">
      <h4 class="mb-4 fw-bold d-flex justify-content-center align-items-center gap-2">
        <i class="bi bi-check2-circle fs-3"></i>
        旅行が終わったら
      </h4>
      <%= render "shared/errors", obj: @plan %>
      <%= form_with model: @plan, url: update_status_plan_path(@plan), method: :patch do |f| %>
        <div class="form-check form-switch d-flex justify-content-center mb-4">
          <%= f.check_box :status, { checked: true, class: "form-check-input" }, "実行済", "未実行" %>
          <%= f.label :status, "「#{@plan.title}」を実行済にする", class: "form-check-label fw-bold text-nowrap" %>
        </div>
        <p class="text-secondary mb-2">※ 訪れなかった所はチェックを外して下さい。</p>
        <%= f.collection_check_boxes :destination_ids, @destinations, :id, :name do |b| %>
          <span class="check-boxes me-2"><%= b.label { b.check_box(checked: true) + b.text } %></span>
        <% end %>
        <div class="d-md-flex align-items-center mt-4 mt-md-5">
          <p class="mb-1 mb-md-0 text-nowrap">思い出の写真を3枚まで追加できます。</p>
          <%= f.file_field :images, multiple: true, class: "form-control form-control-sm" %>
        </div>
        <div class="d-grid col-12 my-4">
          <%= f.submit "更新する", class: "btn btn-info rounded-pill" %>
        </div>
      <% end %>

      <%= link_to "プラン詳細に戻る", plan_path(@plan) %>
    </div>
  </div>
</div>

app/views/plans/new.html.erb
<% provide(:title, "旅行プランを作成する") %>
<div class="container my-2 my-md-4" style="max-width: 900px;">
  <div class="row py-5 d-flex justify-content-center shadow-sm rounded-3 bg-white">
    <div class="col-11 col-sm-9 col-md-8 p-0">
      <h4 class="mb-4 fw-bold text-center">
        <i class="bi bi-chat-dots-fill fs-3 me-1"></i>
        旅行プランを作成する
      </h4>
      <%= render "shared/errors", obj: @plan %>
      <%= form_with model: @plan do |f| %>
        <div class="mb-4">
          <%= f.label :title, class: "required" %>
          <span class="character-limit">25文字以内</span>
          <%= f.text_field :title, placeholder: "例）AI大阪旅", class: "form-control form-control-sm" %>
        </div>
        <%= f.label :start_date, "期間", class: "required" %>
        <div class="mb-3 d-flex justify-content-between align-items-center gap-1 gap-sm-4">
          <%= f.date_field :start_date, class: "form-control form-control-sm" %>
          <span class="text-nowrap">から</span>
          <%= f.date_field :end_date, class: "form-control form-control-sm" %>
        </div>
        <div class="mb-3">
          <p class="mb-1">こちらが選択されています</p>
          <%= f.collection_check_boxes :destination_ids, @selected_destinations, :id, :name do |b| %>
            <span class="check-boxes me-2"><%= b.label { b.check_box(checked: true) + b.text } %></span>
          <% end %>
        </div>
        <div class="mb-5">
          <%= f.label :note %>
          <%= f.text_area :note, placeholder: "旅のメモを入力（AIによる文章生成には影響しません。）", class: "form-control form-control-sm" %>
        </div>
        <%= f.hidden_field :group_id, value: @group_id %>
        <div class="d-grid gap-2">
          <%= f.submit 'AI提案プランを生成（数秒要します）', class: "btn btn-dark bg-gradient rounded-pill shadow-sm" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/plans/show.html.erb
<% provide(:title, @plan.title) %>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-4 col-md-3 d-none d-sm-block ps-0 pe-xl-5">
      <%= link_to group_path(@plan.group_id), class: "d-block m-3 text-decoration-none d-flex justify-content-between align-items-center border-bottom border-2 border-secondary text-dark destinations-link" do %>
        <i class="bi bi-arrow-left fs-6 fs-md-5 ms-1"></i>
        <span>グループ画面へ</span>
        <span class="me-1"></span>
      <% end %>
      <ul class="list-group list-group-flush shadow-sm">
        <% @my_plans.each do |plan| %>
          <li class="list-group-item list-group-item-action list-group-item-light<%= " active" if plan.id == @plan.id %> d-flex justify-content-between align-items-center pe-2">
            <%= link_to plan.title, plan_path(plan.id), class: (plan.id == @plan.id ? "text-white" : "text-body") %>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="col-12 col-sm-8 col-md-9">
      <div class="row">
        <div class="col-12 col-sm-11 p-0">
          <div id='map-show'></div>
          <script>
            function initMap() {
              let map = new google.maps.Map(document.getElementById('map-show'), {
                center: {
                  lat: <%= @plan.destinations.present? ? @plan.destinations.first.latitude : 34.7024854 %>,
                  lng: <%= @plan.destinations.present? ? @plan.destinations.first.longitude : 135.4959506 %>
                },
                zoom: 11,
              });
              let transitLayer = new google.maps.TransitLayer();
              transitLayer.setMap(map);

              <% @plan.destinations.each do |destination| %>
                (function() {
                  let markerLatLng = {
                    lat: <%= destination.present? ? destination.latitude : 34.7024854 %>,
                    lng: <%= destination.present? ? destination.longitude : 135.4959506 %>
                  };
                  let marker = new google.maps.Marker({
                    position: markerLatLng,
                    map: map
                  });
                  //マーカーをクリックしたとき、詳細情報を表示
                  let infowindow = new google.maps.InfoWindow({
                    position: markerLatLng,
                    content: "<a href='<%= destination_url(destination.id) %>'><%= destination.name %></a>"
                  }); //詳細ページへのリンクを表示
                  marker.addListener('click', function() {
                    infowindow.open(map, marker);
                  });
                })();
              <% end %>
            }
          </script>
          <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['MAPS_PLATFORM_API_KEY'] %>&callback=initMap" async defer></script>
        </div>
      </div>
      <div class="row">
        <div class="col-12 col-sm-11 p-3 mb-sm-4 shadow-sm rounded-3 bg-white">
          <div class="d-flex justify-content-between align-items-center mb-2">
            <h4 class="fw-bold mb-0"><%= @plan.title %></h4>
            <%= link_to group_path(@plan.group.id) do %>
              <span class="badge bg-dark bg-gradient rounded-pill p-2 group-link">
                <%= @plan.group.name %>
              </span>
            <% end %>
          </div>
          <div class="d-flex justify-content-end mb-2">
            <p class="mb-2 fw-bold">
              <i class="bi bi-calendar-range me-1"></i>
              <%= l @plan.start_date %> - <%= l @plan.end_date, format: :short %>
            </p>
          </div>
          <% if @plan.status == "実行済" %>
            <div class="alert alert-info py-0 d-flex justify-content-center align-items-center gap-1" role="alert">
              <i class="bi bi-check2-circle fs-4"></i>
              <%= @plan.status %>
            </div>
          <% end %>

          <% if @plan.images.present? %>
            <div class="container p-0 mb-4" style="max-width: 600px;">
              <div class="row d-flex justify-content-center">
                <div class="col-12">
                  <div id="carouselExampleIndicators" class="carousel slide carousel-fade" data-bs-ride="carousel">
                    <div class="carousel-indicators">
                      <% @plan.images.each_with_index do |_, i| %>
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="<%= i %>" class="<%= 'active' if i.zero? %>"></button>
                      <% end %>
                    </div>
                    <div class="carousel-inner">
                      <% @plan.images.each_with_index do |image, i| %>
                        <div class="carousel-item <%= 'active' if i.zero? %>" data-bs-interval="5000">
                          <%= image_tag image.variant(resize: '600x600'), alt: "思い出の写真", class: "plan-image" %>
                        </div>
                      <% end %>
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="visually-hidden">Next</span>
                    </button>
                  </div>
                </div>
              </div>
            </div>
          <% end %>

          <p class="mb-5 p-1 p-md-2 border rounded-3">
            <%= safe_join(@plan.proposed_plan.split("\n"),tag(:br)) %>
          </p>
          <table class="table table-sm">
            <thead class="table-light">
              <tr>
                <th scope="col">分類</th>
                <th scope="col">名称</th>
                <th scope="col" class="d-none d-lg-table-cell">住所</th>
                <th scope="col">状況</th>
                <th scope="col" class="text-nowrap">ユーザー</th>
              </tr>
            </thead>
            <tbody>
              <% @plan_destinations.each do |destination| %>
                <tr>
                  <td class="text-nowrap text-secondary"><%= destination.category.present? ? destination.category.name : "未設定" %></td>
                  <td><%= link_to destination.name, destination_path(destination.id) %></td>
                  <td class="d-none d-lg-table-cell"><%= destination.address %></td>
                  <td class="text-nowrap <%= "text-danger" if destination.status == "未訪問" %>">
                    <%= destination.status %>
                  </td>
                  <td><%= destination.user.name %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <% if @plan.note.present? %>
            <h6 class="fw-bold">メモ</h6>
            <p><%= @plan.note %></p>
          <% end %>
          <% if current_user.group_ids.include?(@plan.group_id) %>
            <p class="text-center d-grid col-8 mx-auto">
              <%= link_to "旅行に行ってきた！", edit_status_plan_path(@plan), class: "btn btn-info mt-4" %>
            </p>
            <%= link_to edit_plan_path(@plan), class: "d-block text-end text-decoration-none" do %>
              <i class="bi bi-pen"></i>
              旅行プランを編集
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>