config/routes.rb
Rails.application.routes.draw do
  root to: 'home#top'
  get '/about', to: 'pages#about'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :users, only: :show
  resources :groups, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :destinations
  resources :plans, only: [:new, :create, :show, :edit, :update, :destroy] do
    member do
      get 'edit_status'
      patch 'update_status'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon.ico' %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-light bg-white">
        <div class="container-md">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="ナビゲーションの切替">
            <span class="navbar-toggler-icon"></span>
          </button>
          <%= link_to about_path, class: "navbar-brand m-0 me-md-4 p-0" do %>
            <%= image_tag 'logo.png', alt: "サイトロゴ", class: "logo" %>
          <% end %>
          <% if user_signed_in? %>
            <div class="dropdown me-md-3">
              <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                <% if current_user.icon.attached? %>
                  <%= image_tag current_user.icon.variant(resize: '100x100'), alt: "アイコン", class: "header-icon rounded-circle" %>
                <% else %>
                  <%= image_tag 'icon_user.png', alt: "アイコン", class: "header-icon rounded-circle" %>
                <% end %>
              </a>
              <ul class="dropdown-menu dropdown-menu-end text-small shadow" aria-labelledby="dropdownUser1">
                <li class="fw-bold text-center mb-1 mx-1">
                  <%= current_user.name %><span class="fw-normal">さん</span>
                </li>
                <li><hr class="dropdown-divider"></li>
                <li>
                  <%= link_to user_path(current_user), class: "dropdown-item" do %>
                    <i class="bi bi-person-fill fs-5"></i>
                    マイページ
                  <% end %>
                </li>
                <li>
                  <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
                    <i class="bi bi-pencil-fill"></i>
                    アカウント編集
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか？" }, class: "dropdown-item" do %>
                    <i class="bi bi-box-arrow-right fs-5"></i>
                    ログアウト
                  <% end %>
                </li>
                <li><hr class="dropdown-divider"></li>
                <li class="text-secondary px-4 fs-small">
                  前回ログイン
                  <span><%= l current_user.last_sign_in_at %></span>
                </li>
              </ul>
            </div>
          <% else %>
            <%= link_to "ゲスト\nログイン", users_guest_sign_in_path, method: :post, class: "btn btn-sm btn-outline-secondary guest-btn lh-sm d-md-none" %>
          <% end %>

          <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav me-auto mb-2 mb-md-0 text-center">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to destinations_path, class: "nav-link" do %>
                    <i class="bi bi-geo-alt-fill"></i>
                    行きたいリスト
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to user_path(current_user), class: "nav-link" do %>
                    <i class="bi bi-person-fill"></i>
                    マイページ
                  <% end %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to new_user_registration_path, class: "btn btn-sm btn-danger d-flex justify-content-center align-items-center gap-1 py-1 mx-5 ms-md-0 me-md-2 mt-4 mt-md-0" do %>
                    <i class="bi bi-pen fs-6"></i>
                    新規登録
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_session_path, class: "btn btn-sm btn-outline-danger d-flex justify-content-center align-items-center gap-1 py-0 mx-5 ms-md-0 me-md-2 my-2 my-md-0 h-100" do %>
                    <i class="bi bi-box-arrow-in-right fs-5"></i>
                    ログイン
                  <% end %>
                </li>
              <% end %>
            </ul>
            <% if user_signed_in? %>
              <%= link_to new_destination_path, class: "btn btn-sm btn-outline-success d-none d-md-block" do %>
                <i class="bi bi-geo-alt-fill"></i>
                行きたい場所を登録
              <% end %>
            <% else %>
              <%= link_to "ゲストログイン", users_guest_sign_in_path, method: :post, class: "btn btn-sm btn-outline-secondary d-none d-md-block" %>
            <% end %>
          </div>
        </div>
      </nav>
    </header>

    <% if notice %>
      <p class="alert alert-success alert-dismissible fade show py-1" role="alert">
        <%= notice %>
        <button type="button" class="btn-close py-2" data-bs-dismiss="alert" aria-label="Close"></button>
      </p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger alert-dismissible fade show py-1" role="alert">
        <%= alert %>
        <button type="button" class="btn-close py-2" data-bs-dismiss="alert" aria-label="Close"></button>
      </p>
    <% end %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>